# Generated by Django 3.2.5 on 2021-09-12 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='rating_average',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='max_members',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
