# Generated by Django 3.2.5 on 2021-09-12 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20210912_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='number_of_members',
        ),
    ]
