# Generated by Django 3.2.5 on 2021-08-30 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_match_number_of_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='sport',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
