# Generated by Django 3.2.5 on 2021-09-16 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_match_number_of_members'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='location',
            new_name='description',
        ),
    ]
